version: '3.8'

services:

  inventory-data-service:
    build:
      context: .
      dockerfile: InventoryDataService/Dockerfile
    ports:
      - "5002:80"

  inventory-service:
    build:
      context: .
      dockerfile: InventoryService/Dockerfile
      args:
        - NUGET_CACHE=/root/.nuget
    volumes:
      - ./InventoryService/appsettings.json:/app/appsettings.json:ro

  api-gateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - inventory-service
    volumes:
      - ./ApiGateway/ocelot.json:/app/ocelot.json:ro