version: '3.8'

services:
  api-gateway:
    build: ./ApiGateway
    ports:
      - "5001:80"
    depends_on:
      - inventory-service
      - inventory-data-service

  inventory-service:
    build: ./InventoryService
    ports:
      - "5000:80"
    environment:
      - DataService__BaseUrl=http://inventory-data-service

  inventory-data-service:
    build: ./InventoryDataService
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=InventoryDb;User=sa;Password=YourStrong@Passw0rd;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=YourStrong@Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - inventory-data:/var/opt/mssql

volumes:
  inventory-data: